GlobalPlanner:      
  old_navfn_behavior: false    #是否使用旧版本导航功能，默认false  
  #是否使用二次逼近的趋势，默认为true，否则使用简单的线性方法 二次近似函数，
  #false使用更简单的计算方式节省硬件资源（否的话会扩展周边4个点，是扩展周边八个）               
  use_quadratic: true          
  use_dijkstra: false          #是否使用D*全局规划算法，默认为true，如果为false，则使用A*算法                 
  use_grid_path: false         #是否沿着网格规划路径，默认为false，false时使用最速下降法计算路径                
  
  allow_unknown:  true         #是否允许规划路径穿越未知区域                 
                                               
  planner_window_x: 0.0       # default 0.0 指定可选窗口的x,y大小以限定规划器的工作空间(程序中未用到)
  planner_window_y: 0.0       # default 0.0
  default_tolerance: 0.0      # default 0.0 允许目标点的误差范围
